export {
  BUILT_IN_SESSION_TEMPLATE_CATALOG_VERSION,
  BUILT_IN_SESSION_TEMPLATES,
  DEFAULT_SESSION_TEMPLATE_PROMPTS,
  DEFAULT_SESSION_TEMPLATES,
  LEGACY_DEFAULT_QUICK_RESPONSES,
  LEGACY_ONLY_SESSION_TEMPLATE_ALIASES,
  findCatalogEntryByExactTemplate,
  normalizePromptForFingerprint,
  promptFingerprint,
} from './sessionTemplateCatalog.js';
