// Re-export everything from db module for backward compatibility
export {
  // Classes
  DatabaseManager,
  BaseRepository,
  ProjectRepository,
  ProjectDefaultsRepository,
  SessionRepository,
  SessionTemplateRepository,
  MessageRepository,
  ConversationRepository,
  CanvasItemRepository,
  TodoRepository,
  WorkLogRepository,
  SessionSummaryRepository,
  AttachmentRepository,
  CommandButtonRepository,
  CommandRunRepository,
  ProviderRepository,
  // Kept for any code that still imports ModelProviderRepository by name
  ModelProviderRepository,
  SettingsRepository,
  AgentCallLogRepository,
  KanbanBoardRepository,
  KanbanLaneRepository,
  KanbanCardRepository,
  // Singleton instances
  databaseManager,
  projects,
  projectDefaults,
  sessions,
  sessionTemplates,
  messages,
  conversations,
  canvasItems,
  todos,
  workLogs,
  sessionSummaries,
  attachments,
  commandButtons,
  commandRuns,
  modelProviders,
  settings,
  agentCallLogs,
  kanbanBoards,
  kanbanLanes,
  kanbanCards,
  // Legacy functions
  initDatabase,
  getDatabase,
  closeDatabase,
  getDbPath,
  generateId,
  transaction,
} from './db/index.js';
