// Re-export everything from db module for backward compatibility
export {
  // Classes
  DatabaseManager,
  BaseRepository,
  ProjectRepository,
  SessionRepository,
  SessionTemplateRepository,
  MessageRepository,
  ConversationRepository,
  CanvasItemRepository,
  SessionNoteRepository,
  TodoRepository,
  WorkLogRepository,
  SessionSummaryRepository,
  AttachmentRepository,
  CommandButtonRepository,
  CommandRunRepository,
  // Singleton instances
  databaseManager,
  projects,
  sessions,
  sessionTemplates,
  messages,
  conversations,
  canvasItems,
  sessionNotes,
  todos,
  workLogs,
  sessionSummaries,
  attachments,
  commandButtons,
  commandRuns,
  // Legacy functions
  initDatabase,
  getDatabase,
  closeDatabase,
  generateId,
  transaction,
} from './db/index.js';
